# This file is generated by nixos-generate-config(8).
# You should copy your actual hardware-configuration.nix here.
# Run 'sudo nixos-generate-config' to generate this file.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # PLACEHOLDER: This is a template hardware configuration
  # You need to replace this with your actual hardware configuration
  # generated by 'sudo nixos-generate-config'
  # 
  # To generate proper hardware config:
  # 1. Boot from NixOS installer
  # 2. Run: sudo nixos-generate-config --root /mnt
  # 3. Copy /mnt/etc/nixos/hardware-configuration.nix to this file
  #
  # For now, using minimal safe defaults that won't break the build

  # Example configuration - REPLACE WITH YOUR ACTUAL HARDWARE CONFIG
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Minimal safe filesystem configuration to prevent build errors
  # IMPORTANT: Replace these with your actual filesystem configuration
  fileSystems."/" = {
    device = "/dev/sda1"; # Update with your actual root device
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/sda2"; # Update with your actual boot device  
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface.
  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
